Repository jslovers/jslovers-official-website, pull requests merged in 2023-11, with the labels that each got.

#28 chore:pr-template added
  .github/pull_request_template.md
Labels: documentation

#30 Update README.md
  README.md
Labels: documentation

#31 doc : add contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: chore

#32 Chore -> Docs to Raise an Issue #24
  README.md
  docs/RaiseIssue.md
Labels: documentation, chore
