Repository jslovers/jslovers-official-website, pull requests merged in 2023-12, with the labels that each got.

#33 chore: Update markdown files
  .github/pull_request_template.md
  CONTRIBUTING.md
  RAISEISSUE.md
  README.md
Labels: documentation, chore

#34 config : add renovate
  renovate.json
Labels: chore

#27 [WIP] - Landing page
  app/(marketing)/layout.tsx
  app/(marketing)/page.tsx
  app/globals.css
  app/page.tsx
  components/Button.tsx
  components/Footer.tsx
  components/Icons.tsx
  components/SectionHeader.tsx
  components/Workshop.tsx
  components/navigation/MainNav.tsx
  config/footer.tsx
  config/marketing.tsx
  lib/utils.tsx
  package-lock.json
  package.json
  postcss.config.js
  public/assets/achievement_1_v1.png
  public/assets/achievement_2_v1.png
  public/assets/achievement_3_v1.png
  public/assets/achievement_4_v1.png
  public/assets/group_demo.png
  public/assets/hero_image_1_v1.png
  public/assets/hero_image_2_v1.png
  public/assets/hero_image_3_v1.png
  public/assets/hero_image_guest_v1.png
  tailwind.config.ts
  types/index.ts
Labels: feat, ui
